# Generated by Django 6.0.2 on 2026-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
