# Generated by Django 6.0.2 on 2026-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
